jcderry5/step-strikers

step-strikers-app/step-strikers-app/Classes/Armor.swift, step-strikers-app/step-strikers-app/Classes/Game.swift, step-strikers-app/step-strikers-app/Classes/RPGCharacter.swift, step-strikers-app/step-strikers-app/Classes/Weapon.swift
Add spells, add useCount and condition to armor and weapon init, add refreshStats
=> Add spells

step-strikers-app/step-strikers-app.xcodeproj/project.pbxproj, step-strikers-app/step-strikers-app/Base.lproj/Main.storyboard, step-strikers-app/step-strikers-app/Battle Screens/BattleIdleViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleRollViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectEquipViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectItemViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/ExtendUIViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/ActionTableViewCell.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/BattleTableStructs.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/EquipTableViewCell.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/ItemTableViewCell.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/StatsHeaderTableViewCell.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/StatsTableViewCell.swift, step-strikers-app/step-strikers-app/RegistrationViewController.swift
5 Screens
Battle Action, Item, Equip, Idle, Roll to Hit
Everything is done programmatically, so to see what the screens do you will need to run it locally. 
All the table views to show what actions, items, or weapons or armor a player can equip is hardcoded at the moment. So is the stats display.
=> Battle Screen Pr

step-strikers-app/StepStrikersTests/CasterUnitTests.swift, step-strikers-app/StepStrikersTests/MessageLogUnitTests.swift, step-strikers-app/step-strikers-app.xcodeproj/project.pbxproj, step-strikers-app/step-strikers-app/Classes/Caster.swift, step-strikers-app/step-strikers-app/Classes/CharacterClasses.swift, step-strikers-app/step-strikers-app/Classes/MessageLog.swift, step-strikers-app/step-strikers-app/Classes/RPGCharacter.swift, step-strikers-app/step-strikers-app/Classes/Weapon.swift
Adding code for message logging and the test cases for them (which all pass)
=> re-adding message log code

step-strikers-app/step-strikers-app/GeneralUIViewControllerExtensions.swift, step-strikers-app/step-strikers-app/LoginViewController.swift, step-strikers-app/step-strikers-app/RegistrationViewController.swift
All extension functions now return the object being created. Developers can now modify objects in ways that the extension functions do not support.
=> Now returning objects in extension file

step-strikers-app/step-strikers-app/LoginViewController.swift, step-strikers-app/step-strikers-app/RegistrationViewController.swift
- Validate password
- Register creates a player and writes dummy data to firebase (It does not create local RPGCharacter)
- Register checks that user entered password and password confirmation matches
=> Better login/register

step-strikers-app/step-strikers-app.xcodeproj/project.pbxproj, step-strikers-app/step-strikers-app/Base.lproj/Main.storyboard, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuHostViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuNonHostViewController.swift
same pr again, this time.. hopefully i can merge
=> Party menu pr

step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Classes/Game.swift, step-strikers-app/step-strikers-app/Classes/RPGCharacter.swift, step-strikers-app/step-strikers-app/LoginViewController.swift, step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift, step-strikers-app/step-strikers-app/Menu Screens/StatsViewController.swift, step-strikers-app/step-strikers-app/Roll Initiative Screens/RollInitiativeViewController.swift
- moved some game functions to the server so there's less hardcoding
- changed global var LocalCharacter to localCharacter since variables should start with lowercase letters
=> Less hardcoding turns again

step-strikers-app/step-strikers-app.xcodeproj/project.pbxproj, step-strikers-app/step-strikers-app/CodeEntryViewController.swift, step-strikers-app/step-strikers-app/LoginViewController.swift, step-strikers-app/step-strikers-app/RegistrationViewController.swift
fixing software keyboard issues with textfields
=> add textfield delegate to remove software keyboard after typing

step-strikers-app/step-strikers-app/Battle Screens/BattleIdleViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/ExtendUIViewController.swift, step-strikers-app/step-strikers-app/Classes/MessageLog.swift, step-strikers-app/step-strikers-app/Roll Initiative Screens/RollResultsViewController.swift
Display messages on the idle screen when other players take action
@alekhyaku the messages are still cut off though :(
=> Add messages firebase

step-strikers-app/step-strikers-app.xcodeproj/project.pbxproj, step-strikers-app/step-strikers-app/HealthKitViewController.swift, step-strikers-app/step-strikers-app/Info.plist, step-strikers-app/step-strikers-app/LoginViewController.swift, step-strikers-app/step-strikers-app/Menu Screens/StatsViewController.swift, step-strikers-app/step-strikers-app/step-strikers-app.entitlements
When in simulator to get the steps count to show up,
1. go to home on the simulator
2. go to the health app
3. go to activity
4. go to steps
5. add data for today in steps
Message me if you need a walkthrough 
The first time you run the simulator a pop up asking for read and write data for the health app will appear, allow both read and write permissions 
It takes... a hot minute to reload new data fyi because my query is big
=> Added Step Count to the stats menu.

step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Classes/CharacterClasses.swift
Filter actions to only show those that can be achieved with the current number of spell points/stamina
=> Filtering Action List based on the player's Stamina/ Spellpoints

step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift
array with strings to display should be reset every time view controller is reloaded.
=> Remove actions table duplicates

step-strikers-app/step-strikers-app/CodeEntryViewController.swift, step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuHostViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuNonHostViewController.swift
Implement backend for creating and joining a team
This is gonna make it hard to test turns until I get team matching done so after approval maybe don't merge it yet idk I'm tired
=> Create and join team

step-strikers-app/step-strikers-app/Classes/Game.swift, step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuHostViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuNonHostViewController.swift, step-strikers-app/step-strikers-app/TeamMatchViewController.swift
Also, I got rid of a bunch of UI stuff in TeamMatchViewController (sorry Alekhya) so make sure those are okay.
To test:
1. pull the new server (very important, nothing will work without the newest version of the server)
2. sign in as 2 players
3. click create team for both
4. make sure the initiative order is the same on both screens and you can get to the battle screens
=> Implement backend for team matching

step-strikers-app/step-strikers-app/Classes/Game.swift, step-strikers-app/step-strikers-app/CodeEntryViewController.swift, step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift
- check whether an action had target or not
- for motivational speech update advantage for whole team
=> Write more info to firebase in endTurn()

step-strikers-app/step-strikers-app/Battle Screens/BattleIdleViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleRollViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectEquipViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectItemViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/ExtendUIViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/BattleTableStructs.swift, step-strikers-app/step-strikers-app/Classes/CharacterClasses.swift, step-strikers-app/step-strikers-app/Classes/Game.swift, step-strikers-app/step-strikers-app/Classes/RPGCharacter.swift, step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift, step-strikers-app/step-strikers-app/Roll Initiative Screens/RollInitiativeViewController.swift, step-strikers-app/step-strikers-app/Roll Initiative Screens/RollResultsViewController.swift
- There's data, but it's not always right until a few rounds in
- Also alekhya randomly fixed overlap
- Also code changed to exclude letters easily mixed up and is now 6 chars long
I will work on other stuff first and then come back and try to fix this but I don't have high hopes
=> Fix stats array

step-strikers-app/step-strikers-app/Battle Screens/BattleSelectEquipViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/ExtendUIViewController.swift, step-strikers-app/step-strikers-app/Classes/CharacterClasses.swift, step-strikers-app/step-strikers-app/Classes/Game.swift
No longer nil while interchanging between using actions and item.
Also fixed minor but in selecting teammates with an index out of bound error.
=> Item functionality [debug]

step-strikers-app/step-strikers-app/TeamMatchViewController.swift
=> Implement back button for team matching screen

step-strikers-app/step-strikers-app/Battle Screens/BattleIdleViewController.swift
My apologies for the stupidest errors anyone has ever seen. Good news is it was an easy fix hehe
=> Fix win/loss

step-strikers-app/step-strikers-app/Battle Screens/BattleIdleViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleRollViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectEquipViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/BattleSelectItemViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/ExtendUIViewController.swift, step-strikers-app/step-strikers-app/Battle Screens/TableViewCells/BattleTableStructs.swift, step-strikers-app/step-strikers-app/BattleResultsLossViewController.swift, step-strikers-app/step-strikers-app/BattleResultsVictoryViewController.swift, step-strikers-app/step-strikers-app/Classes/Item.swift, step-strikers-app/step-strikers-app/Classes/Weapon.swift, step-strikers-app/step-strikers-app/CodeEntryViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuNonHostViewController.swift, step-strikers-app/step-strikers-app/SettingsViewController.swift
=> lots of fixes for things i don't remember now

step-strikers-app/step-strikers-app/SettingsViewController.swift
To test: register as a new player and then delete that account. You should see the player doc disappear on firebase and if you try to sign in as them again it won't work
=> Implement delete account

step-strikers-app/step-strikers-app/Classes/CharacterClasses.swift
Fixing some item names for the help button that were wrong
=> Fix help item names

step-strikers-app/step-strikers-app/Battle Screens/BattleSelectEquipViewController.swift, step-strikers-app/step-strikers-app/Classes/Armor.swift, step-strikers-app/step-strikers-app/Classes/Weapon.swift
1. localCharacters should always have fists and NoArmor by the moment they look to equip something
2. Old Fists and Old NoArmor (>95 users) shall be replaced so we are not running the risk of triple-digit useCounts
=> Fix Bugs with Weapons and Armor

step-strikers-app/step-strikers-app/Menu Screens/BattleMenuViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuHostViewController.swift, step-strikers-app/step-strikers-app/Party Menu Screens/PartyMenuNonHostViewController.swift
To make the leave button I just copied the ready button and put it at a horrible random location, you can reposition. I'm not sure if it should be below or above or have red text or whatever I'll leave that up to you!
=> Hosts can disband team
